webapp/config/routes.rb
Rails.application.routes.draw do
  get 'participations/create'

  get 'participations/destroy'

  get 'static_pages/home'

  get 'static_pages/help'

  resources :users
  root 'static_pages#home'
  
  resources :sessions, only: [:new, :create, :destroy,:edit]
  
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  get "participations/show"
  match 'participations/partner/:id',to:'participations#partner',via:'get'
 
  resources :activities, only: [:create, :destroy,:edit] do
    resources :reviews
    resources :participations
    get "participations/show"
  end
  
  get 'activities/new'
  patch '/activities/:id(.:format)',to: 'activities#update'
  put '/activities/:id(.:format)',to: 'activities#update'
  
  match '/activities/detail/:id(.:format)',to:'activities#detail',via:'get'
  match '/activities/:id',to: 'activities#show', via: 'get'
  
  
  
  
  

end

webapp/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
    <div class="container">
    <%= link_to "抱团网", users_path, id: "logo" %>
    <nav>
    <ul class="nav pull-right">
    
    <% if signed_in? %>
   
    <li id="fat-menu" class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%=current_user.name%><b class="caret"></b></a>
    <% if !current_user.admin?%>
    <ul class="dropdown-menu">
        <li><%= link_to "查看个人信息", current_user %></li>
        <li><%= link_to "修改个人信息", edit_user_path(current_user) %></li>
        <li><%= link_to "已参加活动",  "/participations/show" %></li>
        <li><%= link_to "已发布活动", activity_path(current_user) %></li>
        <li><%= link_to "发布活动", activities_new_path(current_user) %></li>
        
        
    </ul>
    <% end %>
    </li>
    <% else %>
    <% end %>
    <li><%= link_to "退出", signout_path, method: "delete" %></li>
    </ul>
    </nav>
    </div>
    </div>
</header>

webapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Webapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>

  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
  

</body>
</html>