webapp/config/routes.rb
Rails.application.routes.draw do
  get 'participations/create'

  get 'participations/destroy'

  get 'static_pages/home'

  get 'static_pages/help'

  resources :users
  root 'static_pages#home'
  
  resources :sessions, only: [:new, :create, :destroy,:edit]
  
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  get "participations/show"
  match 'participations/partner/:id',to:'participations#partner',via:'get'
 
  resources :activities, only: [:create, :destroy,:edit] do
    resources :reviews
    resources :participations
    get "participations/show"
  end
  
  get 'activities/new'
  patch '/activities/:id(.:format)',to: 'activities#update'
  put '/activities/:id(.:format)',to: 'activities#update'
  
  match '/activities/detail/:id(.:format)',to:'activities#detail',via:'get'
  match '/activities/:id',to: 'activities#show', via: 'get'
  
  
  
  
  

end

webapp/app/models/activity.rb
class Activity < ActiveRecord::Base
    belongs_to :user
    validates :user_id, presence: true
    default_scope -> { order('created_at DESC') }
    has_many :participations, dependent: :destroy
    has_many :reviews, dependent: :destroy
   
end

webapp/app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
    before_action :signed_in_user, only: [:new, :create, :destroy]
    
    def new
    
        @activity=current_user.activities.new
    end
    def edit
        @activity=current_user.activities.find(params[:id])
    end
    
    def create
        @activity = current_user.activities.build(activity_params)
        if @activity.save
            flash[:success] = "Activity created!"
            redirect_to users_path
        else
            render 'sessions/new'
        end
    end
    
    
    
    def update

        @activity=current_user.activities.find(params[:id])
        if @activity.update_attributes(activity_params)
            flash[:success] = '更新成功！'
            redirect_to activity_path(current_user)
        else
            flash[:error]='更新失败！'
            redirect_to edit_activity_path(@activity)
        end
=begin
        @activity=current_user.activities.find(params[:id])
        @activity.update_attributes!(activity_params)
        flash[:notice]='更新完成'
        redirect_to activity_path(current_user)
=end
        
        
    end
    

    def destroy
       Activity.find(params[:id]).destroy
       flash[:success]="删除成功！"
       redirect_to activity_path(current_user)
        
    end
    

    def show
        @user = User.find(params[:id])
        @activities = @user.activities.paginate(page: params[:page])
    
    end
    def detail
        activities=Activity.all
        @activity=activities.find(params[:id])
        
    end


   
    
    
    private
        def activity_params
            params.require(:activity).permit(:title,:style,:introduction,:limitednumber,:starttime,:deadline)
        end
        def correct_activity
            @activity = current_user.activities.find_by(id: params[:id])
            redirect_to root_url if @activity.nil?
        end

end

webapp/app/views/activities/_activity.html.erb
<p>
  <strong>title:</strong>
  <%= activity.title %>
</p>
<p>
  <strong>style:</strong>
  <%= activity.style %>
</p>
<p>
  <strong>limitednumber:</strong>
   <%= activity.limitednumber %>
</p>
<p>
  <strong>starttime:</strong>
  <%= activity.starttime %>
</p>
<p>
  <strong>deadline:</strong>
  <%= activity.deadline %>
</p>

<strong>introduction:</strong>   
<span class="content"><%= activity.introduction %></span>
<br>
<h6>
<%= link_to '编辑',edit_activity_path(activity) %>
<%= link_to "删除", activity, method: :delete, data: { confirm: "确定删除?" } %>
<%= link_to '查看同伴', options={:controller=>"participations",:action=>"partner",:id=>activity.id}%>
</h6>
<HR>
    

webapp/app/views/activities/_activity_form.html.erb
<div align="center">
    <%= form_for(@activity) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        
        
        <div class="field">
            <%= f.label :title %><br>
            <%= f.text_field :title %>
            
        </div>
        
        <div class="field">
            <%= f.label :style %><br>
            <%= f.text_field :style %>
        </div>
        
        <div class="field">
            <%= f.label :introduction %><br>
            <%= f.text_area :introduction, placeholder: "Compose new activity..." %>
        </div>
        
        <div class="field">
            <%= f.label :limitednumber %><br>
            <%= f.text_field :limitednumber %>
        </div>
        
        <div class="field">
            <%= f.label :starttime %><br>
            <%= f.text_field :starttime %>
        </div>
        
        <div class="field">
            <%= f.label :deadline %><br>
            <%= f.text_field :deadline %>
        </div>
        
        <%= f.submit "Post", class: "btn btn-large btn-primary" %>
    <% end %>
</div>

webapp/app/views/activities/detail.html.erb
<h3>活动详情</h3>
<p>
  <strong>title:</strong>
  <%= @activity.title %>
</p>
<p>
  <strong>style:</strong>
  <%= @activity.style %>
</p>
<p>
  <strong>limitednumber:</strong>
   <%= @activity.limitednumber %>
</p>
<p>
  <strong>starttime:</strong>
  <%= @activity.starttime %>
</p>
<p>
  <strong>deadline:</strong>
  <%= @activity.deadline %>
</p>

<strong>introduction:</strong>   
<span class="content"><%= @activity.introduction %></span>
<br>
<%= link_to "参加",new_activity_participation_path(@activity) %>
<%= link_to "评论", new_activity_review_path(@activity)%>

webapp/app/views/activities/edit.html.erb
<%= render 'activities/activity_form' %>

webapp/app/views/activities/new.html.erb
<%= render 'activities/activity_form' %>

webapp/app/views/activities/show.html.erb
    <div class="span8">
        <% if @user.activities.any? %>
            <h3>已发布活动 (<%= @user.activities.count %>)</h3>
            <ol class="activities">
                
                <%= render @activities %>
                
                
                
            </ol>
            <%= will_paginate @activities %>
        <% end %>
    </div>
    
    