webapp/config/routes.rb
Rails.application.routes.draw do
  get 'participations/create'

  get 'participations/destroy'

  get 'static_pages/home'

  get 'static_pages/help'

  resources :users
  root 'static_pages#home'
  
  resources :sessions, only: [:new, :create, :destroy,:edit]
  
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  get "participations/show"
  match 'participations/partner/:id',to:'participations#partner',via:'get'
 
  resources :activities, only: [:create, :destroy,:edit] do
    resources :reviews
    resources :participations
    get "participations/show"
  end
  
  get 'activities/new'
  patch '/activities/:id(.:format)',to: 'activities#update'
  put '/activities/:id(.:format)',to: 'activities#update'
  
  match '/activities/detail/:id(.:format)',to:'activities#detail',via:'get'
  match '/activities/:id',to: 'activities#show', via: 'get'
  
  
  
  
  

end

webapp/app/models/participation.rb
class Participation < ActiveRecord::Base
    belongs_to :user
    belongs_to :activity
    validates :user_id, presence: true
    validates :activity_id, presence: true
end

webapp/app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
  before_action :signed_in_user
  
  def show
    @participations=current_user.participations
    
    
    
  end
  
  def new
      if Activity.find_by_id(params[:activity_id]).user_id!=current_user.id
        if  current_user.participations.find_by_activity_id(params[:activity_id])==nil
          @participation=Activity.find_by_id(params[:activity_id]).participations.build
          @participation.user_id=current_user.id
          @participation.save
          flash[:success]="参加成功！"
          redirect_to users_path
        else if current_user.participations.find_by_activity_id(params[:activity_id]).user_id!=current_user.id
          @participation=Activity.find_by_id(params[:activity_id]).participations.build
          @participation.user_id=current_user.id
          @participation.save
          flash[:success]="参加成功！"
          redirect_to users_path
        else
          flash[:error]="你已经参加了该活动！"
          redirect_to users_path
        end
        end
      else 
        flash[:error]="你已经是活动发起人！"
        redirect_to users_path
      end
      
      #redirect_to "/participations#show"
  end
  def create
     current_user.participations << Activity.find_by_id(params[:activity_id])
     
     
    
  end

  def destroy
    @participation=Participation.find_by_id(params[:id])
    @participation.destroy
    flash[:success]="删除成功！"
    redirect_to users_path
    
  end
  
  def partner
    @participations=Participation.where(:activity_id=>params[:id])
    
  end
  private
    
    
  
end

webapp/app/helpers/participations_helper.rb
module ParticipationsHelper
end

webapp/app/views/participations/partner.html.erb
<h3>参加活动人数(<%=@participations.count%>)</h3>

<table width="600" align="left">
     <thead>
        <tr>
          <th><strong>Name:</strong></th>
          <th><strong>Age:</strong></th>
          <th><strong>Sex:</strong></th>
          <th><strong>Phonenumber:</strong></th>
        </tr>
    </thead>
    
    <tbody align="center">
        <% @participations.each do |participation| %>
        <% @user=User.find(participation.user_id) %>
        <tr>
            <td><%= @user.name %></td>
            <td><%= @user.age %></td>
            <td><%= @user.sex %></td>
            <td><%= @user.phonenumber %></td>
        </tr>
        <% end %>
        
    </tbody>
</table>

webapp/app/views/participations/show.html.erb
<h3>已参加活动(<%=@participations.count %>)</h3>
<% @participations.each do |participation| %>
<% @activity=Activity.find_by_id(participation.activity_id)%>

<p>
  <strong>title:</strong>
  <%= @activity.title %>
</p>
<p>
  <strong>style:</strong>
  <%= @activity.style %>
</p>
<p>
  <strong>limitednumber:</strong>
   <%= @activity.limitednumber %>
</p>
<p>
  <strong>starttime:</strong>
  <%= @activity.starttime %>
</p>
<p>
  <strong>deadline:</strong>
  <%= @activity.deadline %>
</p>

<strong>introduction:</strong>   
<span class="content"><%= @activity.introduction %></span>
<span class="timestamp">
    Posted <%= time_ago_in_words(@activity.created_at) %> ago.
</span><br>
<%=link_to "删除",activity_participation_path(@activity,participation),:method=>"delete",:class=>"btn"%> 
<%=link_to "评论",new_activity_review_path(@activity),:class=>"btn" %>
<%=link_to "查看同伴",options={:controller=>"participations",:action=>"partner",:id=>@activity.id},:class=>"btn"%>

<% end %>