webapp/config/routes.rb
Rails.application.routes.draw do
  get 'participations/create'

  get 'participations/destroy'

  get 'static_pages/home'

  get 'static_pages/help'

  resources :users
  root 'static_pages#home'
  
  resources :sessions, only: [:new, :create, :destroy,:edit]
  
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  get "participations/show"
  match 'participations/partner/:id',to:'participations#partner',via:'get'
 
  resources :activities, only: [:create, :destroy,:edit] do
    resources :reviews
    resources :participations
    get "participations/show"
  end
  
  get 'activities/new'
  patch '/activities/:id(.:format)',to: 'activities#update'
  put '/activities/:id(.:format)',to: 'activities#update'
  
  match '/activities/detail/:id(.:format)',to:'activities#detail',via:'get'
  match '/activities/:id',to: 'activities#show', via: 'get'
  
  
  
  
  

end

webapp/app/models/user.rb
class User < ActiveRecord::Base
    has_many :activities, dependent: :destroy
    has_many :participations, dependent: :destroy
    has_many :reviews, dependent: :destroy
    
    
    validates :password, length: { minimum: 6 }
    
    before_create :create_remember_token
    
    def User.new_remember_token
        SecureRandom.urlsafe_base64
    end
    
    def User.encrypt(token)
        Digest::SHA1.hexdigest(token.to_s)
    end
    
    private
        def create_remember_token
            self.remember_token = User.encrypt(User.new_remember_token)
        end
 
    
    
    
    has_secure_password
end

webapp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  
  before_action :admin_user, only: :destroy

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :department, :studentnumber, :phonenumber, :age, :sex,:password, :password_confirmation)
    end
end

webapp/app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

webapp/app/views/users/_form.html.erb
<div align="center">
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :department %><br>
    <%= f.text_field :department %>
  </div>
  <div class="field">
    <%= f.label :studentnumber %><br>
    <%= f.text_field :studentnumber %>
  </div>
  <div class="field">
    <%= f.label :phonenumber %><br>
    <%= f.text_field :phonenumber %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <%= f.label :sex %><br>
    <%= f.text_field :sex %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

webapp/app/views/users/edit.html.erb
<div align="center">
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :department %><br>
    <%= f.text_field :department %>
  </div>
  <div class="field">
    <%= f.label :studentnumber %><br>
    <%= f.text_field :studentnumber %>
  </div>
  <div class="field">
    <%= f.label :phonenumber %><br>
    <%= f.text_field :phonenumber %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <%= f.label :sex %><br>
    <%= f.text_field :sex %>
  </div>
  <div class="field">
      
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= gravatar_for @user %>
<a href="http://gravatar.com/emails">change</a>
</div>

webapp/app/views/users/index.html.erb
<% if current_user.admin?%>
<% @users.each do |user| %>
<% if !user.admin%>
<ul class="inline">
  <li><%= gravatar_for user %><br><%= user.name %></li>
  <li><%= link_to "delete", user, method: :delete,data: { confirm: "You sure?" } %></li>
</ul>
<% end %>
<% end %>
<% else %>
<p id="notice"><%= notice %></p>

<h1>欢迎来到抱团网，点击参加活动吧！</h1>
<div class="navbar">
  <div class="navbar-inner">
    <p class="brand">分类</p>
    <ul class="nav">
      <li><%= link_to "旅游", '#' %></li>
      <li><%= link_to "美食", '#' %></li>
      <li><%= link_to "学习", '#' %></li>
      <li><%= link_to "游戏", '#' %></li>
      <li><%= link_to "体育", '#' %></li>
      <li><%= link_to "购物", '#' %></li>
    </ul>
  </div>
</div>
<ul class="nav nav-pills">
  <li><%= link_to "最新", '#' %></li>
  <li><%= link_to "最热", '#' %></li>
</ul>


<table width="800">
  <tbody>
    <% @users.each do |user| %>
    <% user.activities.each do |activity| %>
    <tr>
      <td><%= gravatar_for user %><br><%= user.name %></td>
      <td><strong>主题:</strong><%= activity.title %><br>
      <strong>发布时间:</strong><%= activity.created_at %><br><strong>活动开始时间:</strong><%= activity.starttime %> </td>
      <td><%=link_to "详情",options ={:controller=>"activities",:action=>"detail",:id => activity.id},:class=>"btn" %></a><br>
      <%=link_to "评论",new_activity_review_path(activity),:class=>"btn"%></td>
    </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
<% end %>

webapp/app/views/users/new.html.erb
<h1 align="center">New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

webapp/app/views/users/show.html.erb
<div class="row">
<aside class="span4">
<section>
<h1>
<%= gravatar_for @user %>
<%= @user.name %>
</h1>
</section>
</aside>
</div>

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Department:</strong>
  <%= @user.department %>
</p>

<p>
  <strong>Studentnumber:</strong>
  <%= @user.studentnumber %>
</p>

<p>
  <strong>Phonenumber:</strong>
  <%= @user.phonenumber %>
</p>

<p>
  <strong>Age:</strong>
  <%= @user.age %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @user.sex %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>